# Generated by Django 4.0.3 on 2023-01-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('ratenum', models.FloatField()),
                ('ratetext', models.TextField()),
            ],
            options={
                'db_table': 'restaurants',
            },
        ),
    ]
