# Generated by Django 4.0.3 on 2023-02-10 11:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='rest_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_name', models.CharField(max_length=200)),
                ('loc', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=1000)),
            ],
        ),
    ]
