# Generated by Django 4.0.3 on 2023-02-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='restaurantsdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('market_address', models.TextField()),
                ('detail_address', models.TextField()),
                ('food_category', models.TextField()),
                ('market_number', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'restaurants_data',
            },
        ),
    ]
