# Generated by Django 4.1.6 on 2023-02-10 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_rest_data_loc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rest_data',
        ),
    ]
